# Generated by Django 4.2 on 2023-04-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Имя категории"),
                ),
                (
                    "adult",
                    models.BooleanField(
                        default=False, verbose_name="Ограничение для взрослых"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Название")),
                ("author", models.CharField(max_length=200, verbose_name="Имя автора")),
                (
                    "poster",
                    models.ImageField(
                        blank=True, upload_to="covers/", verbose_name="Обложка"
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Цена")),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="categories",
                        to="books.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
    ]
