# Generated by Django 4.2 on 2023-04-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="poster",
            field=models.ImageField(
                blank=True,
                default="default.jpg",
                upload_to="covers/",
                verbose_name="Обложка",
            ),
        ),
    ]
